### ISSUE TITLE
Drill Compile error

### ISSUE THREAD

**Issue by zhanghaicheng1** [apache/drill#2292]
Since my local cluster zookeeper cluster is version 3.4.7, I downloaded Drill version 1.17.0 and used the official package. When the hive data source is selected, the database can be accessed normally, but when the show tables is executed, it prompts 
```
ERROR hive.log-Got exception: org.apache.thrift.TApplicationException Invalid method name:'get_tables_by_type'
```
Drill version ：1.17.0
![image](https://user-images.githubusercontent.com/46189785/128829102-47feeff8-13bc-49c7-9472-559f0aba6d7d.png)

Therefore, I lowered the hive version to 2.1.1 to try. The picture below shows the error I encountered during compilation. I look forward to the author's reply! Thanks!

![image](https://user-images.githubusercontent.com/46189785/128828519-08abbc40-4037-4e52-843f-a1a9ddf70c61.png)

**Comment by luocooong** [comment]
Have you solved the problem?
