### ISSUE TITLE
Error message: Hostname 192.168.30.10 not verified:

### ISSUE THREAD

**Issue by tamermh** [apache/drill#2329]
Hi,

i am trying to use http plugin to connect to a local server that has self signed certificate and i am getting the following messege when i run  a query

org.apache.drill.common.exceptions.UserRemoteException: DATA_READ ERROR: Failed to read the HTTP response body

Error message: Hostname 192.168.30.10 not verified:
    certificate: sha256/g/W9segvBmGap2pfdFU2WZ7LdHnsJiMf+9BDTkLc1kc=
    DN: CN=mydomain.com, O=Support, L=McLean, ST=VA, C=US
    subjectAltNames: []
Connection: actiondetails
Plugin: http1
URL: https://192.168.30.10/library/code.json?id=6110

i tried to add the certificate to the java but no luck.

how can i fix this issue? or how can i disable certificate verification in Drill? thanks in advance

**Comment by dzamo** [comment]
Closing, this looks like a misconfigured cert.  Please feel free to continue to chat with us in Slack or the mailing lists for assistance.
