### ISSUE TITLE
Query Profiles Error

### ISSUE THREAD

**Issue by CuteKittyhoho** [apache/drill#2350]
**Describe the bug**
After I launch  a drillbit from Eclipse (See tutorial here: https://github.com/paul-rogers/drill/wiki/Launch-a-Drillbit-From-Eclipse), I logged into localhost:8047 to see if Drill functions well, and basically it did. But when I submitted a query and click the tag "Profile" to see the profile of this query, a error with error message was reported:
```
RESOURCE ERROR: Failed to get profiles from persistent or ephemeral store.\n\n\n[Error Id: f4c362c7-124d-452a-a209-82633ca6098e ]
```
Fortunately, I fixed this problem by chance, and the operation is quite simple: open the debug configuration of Eclipse, then add `DRILL_LOG_DIR =/a path directed to a certain directory` in the Environment tab. However, I can not see underlying relationship between the two things, so I deemed this as a bug and report it here.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser: Firefox
 - Version: Drill 1.20 snapshot

**Comment by cgivre** [comment]
@jnturton Can we close this issue?

**Comment by jnturton** [comment]
I've added this information to the relevant Dev wiki page, thank you for sharing it.
