### ISSUE TITLE
JQuery Vulnerability issue (JQuery Update request) 

### ISSUE THREAD

**Issue by fromrymail** [apache/drill#2380]
The apache drill used JQuery around 3.4.0 or related UI jquery. 

However we have the vulnerability report form CVE
https://snyk.io/vuln/npm:jquery

Can you update the this JQuery version 3.4.0 to 3.6.0 for windows exe file?

**Comment by kingswanwho** [comment]
Hi, I can try to update it.

**Comment by fromrymail** [comment]
> Hi, I can try to update it.

Thank you so much.
