### ISSUE TITLE
Update the copyright year [for newcomers]

### ISSUE THREAD

**Issue by luocooong** [apache/drill#2439]
**Describe the bug**

We need to update the copyright year in `NOTICE` files (this repository), and some resource files on the [drill-site](https://github.com/apache/drill-site) project.

apache/drill :
drill/NOTICE
drill/distribution/src/main/resources/NOTICE

apache/drill-site :
drill-site/_includes/footer.html
and more?

**Expected behavior**

You can refer to this [pull request](https://github.com/apache/drill/commit/c4083ad81813b1e37dd28d8046065122ad63b9c7) to submit your contribution, thank you.

**Additional context**

1. `apache/drill` is the codebase, `apache/drill-site` is the website, we should make a separate pull request.
2. If you would like to know about the process of contribution, refer to [Help beginners to contribute to open source projects](https://github.com/firstcontributions/first-contributions).
2. Please let us know if you need any help, [mailing list](https://drill.apache.org/mailinglists/) and [Slack](https://bit.ly/3t4rozO).

**Comment by pjfanning** [comment]
The codebase updates are done - site ones may still be needed.

**Comment by pjfanning** [comment]
@luocooong I updated the drill-site/_includes/footer.html - what is needed to get the site to republish with the change?

**Comment by luocooong** [comment]
@pjfanning Thank you for receiving this task. No more operation is actually required. Automatically published after the pull request has merged.

**Comment by jnturton** [comment]
If everything's working properly then you just need to wait ~3 minutes 
and then force your browser to fetch an uncached copy from 
http://drill.apache.org.
