### ISSUE TITLE
SAS format plugin. Select fails if the first row contains null values

### ISSUE THREAD

**Issue by pseudomo** [apache/drill#2466]
Select from dfs.`path_to_sas_file` fails with error "Cannot invoke "Object.getClass()" because "this.firstRow[counter]" is null"
 if the first row of sas file contains null values.

Can be reproduced with any sas file that contain null values in the first row.
Apparently, the problem is here:
drill\contrib\format-sas\src\main\java\org\apache\drill\exec\store\sas\SasBatchReader.java

```
private TupleMetadata buildSchema() {
    SchemaBuilder builder = new SchemaBuilder();
    List<Column> columns = sasFileReader.getColumns();
    int counter = 0;
    for (Column column : columns) {
      String fieldName = column.getName();
      try {
        MinorType type = getType(**firstRow[counter].getClass()**.getSimpleName());
        if (type == MinorType.BIGINT && !column.getFormat().isEmpty()) {
          logger.debug("Found possible time");
          type = MinorType.TIME;
        }
        builder.addNullable(fieldName, type);
      } catch (Exception e) {
        throw UserException.dataReadError()
          .message("Error with column type: " + firstRow[counter].getClass().getSimpleName())
          .addContext(errorContext)
          .build(logger);
      }
      counter++;
    }

    return builder.buildSchema();
  }
```

![image](https://user-images.githubusercontent.com/11786376/154575424-1bb86df3-8a1f-4477-93a1-2b97d7c09fbc.png)

**Comment by cgivre** [comment]
@pseudomo 
Thanks for posting.  Could you share a file with `null` values in the first row so that we can test a fix?

**Comment by pseudomo** [comment]
> @pseudomo Thanks for posting. Could you share a file with `null` values in the first row so that we can test a fix?

Unfortunately, I can't share the file here since it contains sensitive information and I don't know how to create one for testing.

**Comment by pseudomo** [comment]
@cgivre,
Many thanks! It will work for me since I build Drill from source.

**Comment by cgivre** [comment]
@pseudomo I submitted a fix.  Could you please try this out with your data?

**Comment by pseudomo** [comment]
> @pseudomo I submitted a fix. Could you please try this out with your data?

Thanks for fixing the issue ! I can now query my file with Drill. 
I got some more real world SAS files to work with and faced new issues. I will report those issues as soon as I get a chance.

**Comment by cgivre** [comment]
> > @pseudomo I submitted a fix. Could you please try this out with your data?
> 
> Thanks for fixing the issue ! I can now query my file with Drill. I got some more real world SAS files to work with and faced new issues. I will report those issues as soon as I get a chance.

Oh no!  Well, I'm glad we got that one working at least.  I don't have a way to generate test data, so it was very hard to test this plugin.  Please send that privately, and I'll work up fixes.
