### ISSUE TITLE
Support RDBMS update, INSERT,delete

### ISSUE THREAD

**Issue by weijunlu** [apache/drill#2561]
How to support RDBMS UPDATE, DELETE, and INSERT SQL statements with JdbcStoragePlugin

**Comment by luocooong** [comment]
@cgivre Does your company have such a demand?

**Comment by cgivre** [comment]
Yes actually.  We've discussed working on this and looked into it a bit.  Our priority would be INSERT statements.  The good news is that Calcite already supports it, so the framework is already there.  We'd just have to write a handler so that Drill knows what to do with the query plan.

**Comment by cgivre** [comment]
> Yes actually. We've discussed working on this and looked into it a bit. Our priority would be INSERT statements. The good news is that Calcite already supports it, so the framework is already there. We'd just have to write a handler so that Drill knows what to do with the query plan.

I actually started a branch with some experimentation for this.  Take a look if you'd like: 
https://github.com/cgivre/drill/tree/add_insert

**Comment by weijunlu** [comment]
@cgivre Ok, thank you very much!

**Comment by wschung1113** [comment]
Any updates on CUD functionalities on RDBMS? @cgivre
