### ISSUE TITLE
Multiarch docker image

### ISSUE THREAD

**Issue by hkad98** [apache/drill#2589]
**Is your feature request related to a problem? Please describe.**
I use MacBook with Apple Silicon, and unfortunately, the docker image on the docker hub is not built for that which may result in performance issues, and even it does not have to work. 

**Describe the solution you'd like**
I want the apache/drill docker image to be built as a multiarch working on several CPUs.

**Comment by luocooong** [comment]
@hkad98 Hi, Welcome.
What CPU architecture do you want to support? AMD64 and ARM64？

**Comment by hkad98** [comment]
@luocooong Yes. I think that AMD64 and ARM64 should be enough.

**Comment by luocooong** [comment]
Okay, let's first look at the publishing process for docker images of other CPU architectures on the docker-hub. Provide docker tag for ARM64 as soon as possible.

**Comment by hkad98** [comment]
@luocooong, I have good news! I was able to build arm based docker image on my MacBook without any modification of the source code, so the only thing that we will need to edit is how the docker image is built for the docker hub.

I suggest trying out the following:

docker buildx build --platform linux/arm64/v8, linux/amd64 *the rest of parameters*

**Comment by luocooong** [comment]
@hkad98 Thank you for provide us the build commands. Indeed, the source code of Drill is fully supported by the aarch64 processor. And any new pull request will be run the unit test on Travis CI(based on ARM64).

**Comment by cgivre** [comment]
@luocooong @hkad98 Can we close this issue?

**Comment by hkad98** [comment]
@cgivre I do not see a docker image supporting ARM-based CPU, so I think that the issue is still actual and should not be closed.

**Comment by jnturton** [comment]
@hkad98 we can close here anyway since I've promoted this to Jira issue [DRILL-8260](https://issues.apache.org/jira/browse/DRILL-8260). You can add yourself as a watcher there to be notified of progress. Thanks for this good idea.

**Comment by hkad98** [comment]
@jnturton Thanks for the link. In that case, it is alright that it is closed. Thanks for your help.
