### ISSUE TITLE
Error when using NEARESTDATE: Unknown variable or type "DateConversionUtils"

### ISSUE THREAD

**Issue by C0ntroller** [apache/drill#2773]
**Describe the bug**
In my query I used the [documented function `NEARESTDATE`](https://drill.apache.org/docs/date-time-functions-and-arithmetic/#nearestdate) and it failed with the mentioned error.

The query in question looks like:
```sql
SELECT COUNT(*), NEARESTDATE(a_column, 'MINUTE') FROM `oracle`.`username`.`V_EXP_PDM_ET610001_87` GROUP BY NEARESTDATE(a_column, 'MINUTE')
```

**To Reproduce**
1. Install (download and unpack) Apache Drill
2. Prepare any data source that has a column with type of `TIMESTAMP`
3. Query anything and use the function `NEARESTDATE`
4. See the error in logs

**Expected behavior**
Function works as intended and documented

**Error detail, log output or screenshots**
Long stacktrace that states multiple times `Unknown variable or type "DateConversionUtils"`

**Drill version**
1.21.0

**Additional context**
[Full stacktrace](https://pastebin.com/pADGacPQ)

**Comment by cgivre** [comment]
@C0ntroller 
Thanks for reporting this.  Good news is that it has already been fixed: (https://github.com/apache/drill/pull/2769)   
We're in the process of releasing a bugfix release 1.21.1 which hopefully will be out either this week or next.  In the meantime, you can build from `master` and  this will work.
