### ISSUE TITLE
Cannot run dockerized Drill in detached mode

### ISSUE THREAD

**Issue by rstoughton** [apache/drill#2790]
**Describe the bug**

I am trying to run Drill in docker on my local machine in detached mode. The container keeps exiting about ~12 seconds after running the command specified in the documentation (https://drill.apache.org/docs/running-drill-on-docker/#running-the-drill-docker-container-in-detached-mode)

**To Reproduce**

```
docker run --name drill-detached \
    -p 8047:8047 \
    -p 31010:31010 \
    --detach apache/drill:1.21.0
```

**Expected behavior**

The container continues to run in the background.

**Error detail, log output or screenshots**

The container exits after roughly 12 seconds with the following output. Note the `%`.

<img width="511" alt="Screen Shot 2023-04-07 at 2 14 21 PM" src="https://user-images.githubusercontent.com/98769863/230664559-d32e9b6c-cb29-4296-b968-7b8dda78c0af.png">

**Drill version**

`1.21.0`

**Additional context**

N/A

**Comment by jnturton** [comment]
Here's a relevant discussion from the Drill mailing list. Also consider a single-node Drill cluster (with a ZooKeeper) using [the distributed mode Docker Compose scripts here](https://github.com/apache/drill/tree/master/distribution/docker-cluster-mode).

Subject:
Re: Running drill in background in embedded mode
From:
James Turton <dzamo@apache.org>
Date:
2022/07/19, 07:28
To:
user@drill.apache.org, Prabhakar Bhosale <bhosale.p.v@gmail.com>

Well if we're playing with hacks... 😄

nohup drill-embedded -f <(sleep infinity) > /dev/null

That needs a shell smart enough to do process substitution and avoids what I guess was busy wait loop in sqlline's input reader that you ran into.

Back to being boring and responsible: are you sure you want to run Drill this way? It would be a lot more natural to launch a standalone Drillbit with drillbit.sh, having started a ZooKeeper somewhere beforehand.
