### ISSUE TITLE
ANALYZE is not supported for group scan with format Delta

### ISSUE THREAD

**Issue by kmatt** [apache/drill#2809]
**Describe the bug**

Attempting to store table metadata in the Iceberg metastore, Delta tables which are queryable with SQL throw error when attempting ANALYZE TABLE

**To Reproduce**

    apache drill (delta.root)> ANALYZE TABLE "path/to/table" REFRESH METADATA 'TABLE' LEVEL;                                                                                                                                                              
    
**Error detail, log output or screenshots**

    Error: VALIDATION ERROR: ANALYZE is not supported for group scan [DeltaGroupScan [path="/path/to/table", entries=[ReadEntryWithPath [path=/path/to/table/partition/file.snappy.parquet], ...

**Drill version**

Apache Drill 1.21.1

**Additional context**

On same Drillbit, ANALYZE is successful on plain Parquet tables.

**Comment by kmatt** [comment]
https://issues.apache.org/jira/browse/DRILL-8440

**Comment by vvysotskyi** [comment]
It is not a bug, but a feature request. Currently, metastore doesn't support the Delta format plugin and the error message states that. In future, this functionality could be added.

**Comment by kmatt** [comment]
Closing as not an issue with this plugin.
