### ISSUE TITLE
JDBC  execute more than one sqls in same connection ,drill report exception msg in drill.log with info level

### ISSUE THREAD

**Issue by yaozhu** [apache/drill#2830]
Before submitting a bug report, please verify that you are using the most current version of Drill.  

Drill jdbc  execute more than one sqls in same connection ,drill report exception msg in drill.log with info level

reproduce stop follow this:
//mysql datasource
//create table  t1 (a int, b varchar(100), c varchar(100))
//insert into t1 values( 1, 'aaa','bbbb');
String sql = "select * from t1 limit 1";
try {
	Statement stmt  = conn.createStatement();
	for (int i = 0 ; i < 4 ; ++i)
	{
		stmt.executeQuery(sql);
	}
	System.out.println("DONE!");

} catch (SQLException e) {
	e.printStackTrace();
}finally {
	conn.close();
}

![image](https://github.com/apache/drill/assets/13361571/68a95252-d3d4-4cc6-bb28-d77492261ebd)

**Comment by cgivre** [comment]
@yaozhu This is a documented behavior of Drill.

**Comment by jnturton** [comment]
You can run as many queries as you like on a single connection but please complete the execution of each query by scrolling through its ResultSet cursor before starting another one.
