### ISSUE TITLE
Query results caching

### ISSUE THREAD

**Issue by RayetSena** [apache/drill#2881]
Hello, 

I am using http storage plugin and I want to activate the caching. In the documentation it says that this requires adding cacheResults. So I added this to my config. But when I run the same query again, there is almost no difference in query duration. You can see the configuration and query duration below.

![image](https://github.com/apache/drill/assets/55273803/2214311b-e359-401f-8abe-60f4bbb9b099)
```
{
  "type": "http",
  "cacheResults": true,
  "connections": {
    "opendata": {
      "url": "https://opendata.cbs.nl/ODataApi/odata/",
      "requireTail": true,
      "method": "GET",
      "authType": "none",
      "inputType": "json",
      "xmlDataLevel": 1,
      "postParameterLocation": "QUERY_STRING",
      "verifySSLCert": false
    }
  },
  "timeout": 4000,
  "retryDelay": 5000,
  "proxyType": "direct",
  "authMode": "USER_TRANSLATION",
  "enabled": true
}
```
![image](https://github.com/apache/drill/assets/55273803/4c90c486-4487-4c47-bc44-6f3b45819341)

Also I tried to configure the caching properties in the drill-override.conf file. Here is the configuration that I added:
```
drill.exec: {
    caching: {
	enabled: true
	storage:{
           type: “local”
           path:  “cache/directory”
        }
    }
}
```

**Drill version**
1.21.1

**Comment by RayetSena** [comment]
When I test using an older version(1.20.1), I can see the query result files under the tmp/http-cache directory, but when I test using a newer version(1.21.1), there are no query result files in that directory, it only contains the journal.

**Comment by jnturton** [comment]
Promoted to [DRILL-8487](https://issues.apache.org/jira/browse/DRILL-8487).
