### ISSUE TITLE
Images for version 1.21.2 not present in docker hub

### ISSUE THREAD

**Issue by slafon51** [apache/drill#2919]
Hello,

The docker images for the version 1.21.2 are not present in the docker hub (https://hub.docker.com/r/apache/drill).

Are you planning to add them in the next few days ?
Thanks you.

Best regards.

**Comment by jnturton** [comment]
@vvysotskyi are you able to assist here?

**Comment by tooptoop4** [comment]
boomp

**Comment by jnturton** [comment]
@tooptoop4 I've got the needed access and I'm looking into it.

**Comment by tooptoop4** [comment]
🙏

**Comment by tooptoop4** [comment]
⏳
