### ISSUE TITLE
Apache Drill website no longer exists?

### ISSUE THREAD

**Issue by Jeducious** [apache/drill#2924]
**Describe the bug**
Try opening this link [http://drill.apache.org/](http://drill.apache.org) you should get the Apache drill website.

I get.... this 
![image](https://github.com/apache/drill/assets/34228929/6bce1b6d-01a3-4e87-9645-658ec45cac0c)

None of the other links appear to work either.

**Comment by jnturton** [comment]
I can't reproduce this. I can see that the link you pasted above includes a trailing "/l" in the URL.

**Comment by Jeducious** [comment]
Hi @jnturton, that trailing / in the url is a mistake which I've corrected now.

Also, if you look at the picture I posted, you can see that the home page URL I used is correct, but still doesn't work for me. Not sure why though. Our group was trying to open the website, and we're remote, so we're on different networks, different ISPs, none of us could get the home page to load.

**Comment by pjfanning** [comment]
There was an issue with a number of apache.org websites this morning but they appear to be fixed now.

**Comment by Jeducious** [comment]
Confirmed this is fixed for me now, website now displaying properly.
