### ISSUE TITLE
Can't configure Mongo UL with query parameter

### ISSUE THREAD

**Issue by mathieuruellan** [apache/drill#2942]
Before submitting a bug report, please verify that you are using the most current version of Drill.  

**Describe the bug**
I'm configuring the mongo connector with an url containing query parameters. The JSON is rejected because "invalid"

**To Reproduce**
1. Go to Drill UI/Storage/Mongo/Update

2. edit the json and enter a valid mongo url with query parameter
 for instance: "connection": mongodb+srv://admin:XXXXXX@localhost:4117/myDB?readPreference=secondaryPreferred",

Please retry: Invalid JSON: Failure when decoding plugin JSON

![image](https://github.com/user-attachments/assets/c7fbd5f0-b3fc-4d32-a760-aa7f48ea99c5)

**Comment by mathieuruellan** [comment]
(the screenshot has a typo with a missing quote), but the issue is still valid

**Comment by cgivre** [comment]
@mathieuruellan  I think the `batchSize` is not a valid parameter.  Try removing that and see if it works.   The problem that you're having is that you've added some parameter that doesn't exist in the Mongo config.

**Comment by mathieuruellan** [comment]
Actually, it was a specific parameter "authMechanism=DEFAULT" not supported because the driver and its mongo url parser is old.
Problem solved.
